"""Removed unnecessary columns

Revision ID: 49e38d35ab9c
Revises: c6c8b17525df
Create Date: 2024-04-14 10:50:57.522058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e38d35ab9c'
down_revision: Union[str, None] = 'c6c8b17525df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'phone')
    op.drop_column('restaurant', 'website')
    op.drop_column('restaurant', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurant', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurant', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
